import Link from "next/link";
import "./../public/css/global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/articles">Articles</Link>
          <Link href="/auteurs">Auteurs</Link>
        </nav>

        <div class="topnav">
          <a class="active" href="#home">
            Tutoriel Next
          </a>
          <a href="#contact">Liste des articles</a>
        </div>

        <div className="main"> {children}</div>
      </body>
    </html>
  );
}
